OS-100   [FE] Create Delivery details
Vadim-Kostetskyi/Online-store pull request #78
Opened 2024-04-06 20:06 UTC by Vadim-Kostetskyi

2024-04-21 17:06 UTC, Vadim-Kostetskyi commented on src/hooks/use-extract-from-path.ts
> +  const navigate = useNavigate();
the page does not reload, so it is needed to track the stage

2024-04-21 17:17 UTC, Vadim-Kostetskyi commented
![image](https://github.com/Vadim-Kostetskyi/Online-store/assets/113288447/536c5103-7228-4554-bf6c-b158cec162ff)
![image](https://github.com/Vadim-Kostetskyi/Online-store/assets/113288447/d15206f3-0831-48ea-b244-2a74db2ae89e)

2024-06-24 06:37 UTC, denred requested changes

2024-06-24 06:37 UTC, denred commented on src/modules/checkout/containers/OrderCheckoutAuthorization/index.tsx
> +import { useNavigate } from 'react-router-dom';
use Link for buttons, it seems that useNavigate is not needed here

2024-06-24 06:37 UTC, denred commented on src/modules/core/components/Input/index.tsx
> +  );
It does not work because Object.keys re-renders every time

2024-06-24 06:37 UTC, denred commented on src/modules/core/components/Input/index.tsx
> +  );
just use clsx

2024-06-24 06:37 UTC, denred commented on src/modules/core/components/Input/index.tsx
> +          {text}
it seems like it would be nice to create a separate component for Input

2024-06-24 06:37 UTC, denred commented on src/modules/order/components/DeliveryInfo/index.tsx
> +            {isHome ? null : <span className={priceClassName}>{price}</span>}
if isHome boolean you can use 
`{ !isHome &&  <span> }`

2024-06-24 06:37 UTC, denred commented on src/modules/order/components/PersonalData/data.ts
> +  | 'state';
it's okay, but a little strange, we can use enum or const object

2024-06-24 06:37 UTC, denred commented on src/modules/order/components/PersonalData/data.ts
> +  | { id: PersonalDataItemId; placeholder: string; type?: undefined };
the same

2024-06-24 06:37 UTC, denred commented on src/modules/order/components/PersonalData/index.tsx
> +  );
why don't you make the BE request?

2024-07-22 12:42 UTC, merged